Core_UdemyProje/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_UdemyProje.Controllers
{
    public class SkillController : Controller
    {

        SkillManager skillManager = new SkillManager(new EfSkillDal());



        public IActionResult Index()
        {
            ViewBag.v1 = "Yetenek Listesi";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Listesi";
            var values = skillManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.v1 = "Yetenek Ekleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Ekleme";
            return View();
        }

        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.TGetByID(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Güncelleme";
            var values = skillManager.TGetByID(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }

    }
}

Core_UdemyProje/Views/Skill/AddSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <p class="card-description"> Yeni Yetenek Ekleme Paneli </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>Başlık</label>
                  @Html.TextBoxFor(x=>x.Title,new {@class="form-control"})
                </div>
                <div class="form-group">
                    <label>Değer</label>
                    @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary me-2">Kaydet</button>
                <button class="btn btn-dark">İptal</button>
            </form>
        </div>
    </div>
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-master/template/assets/vendors/js/vendor.bundle.base.js"></script>

Core_UdemyProje/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Düzenleme Sayfası</h3>
</div>

@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">

                <p class="card-description"> Yetenek Düzenleme Paneli </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.SkillID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Değer</label>
                        @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary me-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>

}

<script src="~/corona-free-dark-bootstrap-admin-template-master/template/assets/vendors/js/vendor.bundle.base.js"></script>

Core_UdemyProje/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi Tablosu</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Başlık</th>
                <th scope="col" class="sort" data-sort="status">Oran</th>
                <th scope="col">Sil</th>
                <th scope="col" class="sort" data-sort="completion">Düzenle</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">

            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @item.SkillID
                    </th>
                    <td class="budget">
                        @item.Title
                    </td>
                  
            
                    <td>
                        <div class="d-flex align-items-center">
                            <span class="completion mr-2">@item.Value %</span>
                            <div>   
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width:@item.Value%;"></div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="dropdown">
                           
                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    </td>

                    <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-info">Güncelle</a></td>
                </tr>

            }

        </tbody>
    </table>
 
    <a href="/Skill/AddSkill" class="btn btn-primary">Yeni Yetenek Ekle</a>
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-master/template/assets/vendors/js/vendor.bundle.base.js"></script>